name: pbrowser
description: "A secure, lightweight WebView browser with navigation UI and embedded proxy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  
  # WebView
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.0
  
  # Network
  http: ^1.1.0
  
  # Database
  drift: ^2.20.3
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # State Management
  provider: ^6.1.2
  
  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.5.4
  intl: ^0.20.1
  sqlite3: ^3.1.6
  flutter_foreground_task: ^9.2.0
  sqlcipher_flutter_libs: ^0.7.0+eol
  flutter_secure_storage: ^10.0.0
  animations: ^2.1.1
  lottie: ^3.3.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  
  # Code Generation
  drift_dev: ^2.20.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo.png"
