name: pbrowser
description: "A secure, lightweight WebView browser with navigation UI and embedded proxy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # WebView
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.0
  webview_windows: ^0.4.0
  window_manager: ^0.4.3
  
  # Network
  http: ^1.1.0
  
  # Database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # State Management
  provider: ^6.1.0
  
  # Utilities
  uuid: ^4.3.0
  shared_preferences: ^2.5.4
  ffi: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  
  # Code Generation
  drift_dev: ^2.16.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#111111"
  image: "assets/images/logo.png"
