import 'device_preset.dart';
import 'behavior_profile.dart';

class PresetRepository {
  static final List<DevicePreset> presets = [
    // --- HIGH-END APPLE (Weight: 5-10) ---
    DevicePreset(
      id: 'mac_m1_2021', name: 'MacBook Pro M1 (2021)', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      platform: 'MacIntel', hardwareConcurrency: 8, deviceMemory: 8, devicePixelRatio: 2.0,
      screenWidth: 1440, screenHeight: 900, viewportWidth: 1440, viewportHeight: 790,
      gpuVendor: 'Apple', gpuRenderer: 'Apple M1', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'America/New_York', locale: 'en-US', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp8"'],
      behaviorProfile: BehaviorProfile.getProfile('low'), networkProfile: {'type': 'broadband', 'latency': 20}, weight: 15,
    ),
    DevicePreset(
      id: 'mac_m2_2023', name: 'MacBook Pro M2 (2023)', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15',
      platform: 'MacIntel', hardwareConcurrency: 8, deviceMemory: 8, devicePixelRatio: 2.0,
      screenWidth: 1440, screenHeight: 900, viewportWidth: 1440, viewportHeight: 790,
      gpuVendor: 'Apple Inc.', gpuRenderer: 'Apple M2', webglVersion: 'WebGL 2.0', touchPoints: 0,
      timezone: 'Europe/London', locale: 'en-GB', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/mp4; codecs="hev1"'],
      behaviorProfile: BehaviorProfile.getProfile('low'), networkProfile: {'type': 'broadband', 'latency': 15}, weight: 10,
    ),
    DevicePreset(
      id: 'iphone_15_pro', name: 'iPhone 15 Pro', category: 'mobile',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
      platform: 'iPhone', hardwareConcurrency: 6, deviceMemory: 8, devicePixelRatio: 3.0,
      screenWidth: 393, screenHeight: 852, viewportWidth: 393, viewportHeight: 720,
      gpuVendor: 'Apple Inc.', gpuRenderer: 'Apple GPU', webglVersion: 'WebGL 2.0', touchPoints: 5,
      timezone: 'America/Los_Angeles', locale: 'en-US', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 2, 'videoInput': 2, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/mp4; codecs="hev1"'],
      behaviorProfile: BehaviorProfile.getProfile('low'), networkProfile: {'type': '5G', 'latency': 35}, weight: 10,
    ),
    DevicePreset(
      id: 'iphone_16_pro', name: 'iPhone 16 Pro', category: 'mobile',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1',
      platform: 'iPhone', hardwareConcurrency: 6, deviceMemory: 8, devicePixelRatio: 3.0,
      screenWidth: 393, screenHeight: 852, viewportWidth: 393, viewportHeight: 720,
      gpuVendor: 'Apple Inc.', gpuRenderer: 'Apple GPU', webglVersion: 'WebGL 2.0', touchPoints: 5,
      timezone: 'America/New_York', locale: 'en-US', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 2, 'videoInput': 2, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/mp4; codecs="hev1"'],
      behaviorProfile: BehaviorProfile.getProfile('ultra_low'), networkProfile: {'type': '5G', 'latency': 30}, weight: 5,
    ),

    // --- MID/LOW APPLE (Weight: 30-50) ---
    DevicePreset(
      id: 'mac_air_m1', name: 'MacBook Air M1', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
      platform: 'MacIntel', hardwareConcurrency: 8, deviceMemory: 8, devicePixelRatio: 2.0,
      screenWidth: 1440, screenHeight: 900, viewportWidth: 1440, viewportHeight: 790,
      gpuVendor: 'Apple', gpuRenderer: 'Apple M1', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'America/Chicago', locale: 'en-US', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp8"'],
      behaviorProfile: BehaviorProfile.getProfile('low'), networkProfile: {'type': 'broadband', 'latency': 25}, weight: 45,
    ),
    DevicePreset(
      id: 'iphone_11', name: 'iPhone 11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
      platform: 'iPhone', hardwareConcurrency: 6, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 414, screenHeight: 896, viewportWidth: 414, viewportHeight: 715,
      gpuVendor: 'Apple Inc.', gpuRenderer: 'Apple GPU', webglVersion: 'WebGL 2.0', touchPoints: 5,
      timezone: 'Europe/London', locale: 'en-GB', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/mp4; codecs="hev1"'],
      behaviorProfile: BehaviorProfile.getProfile('medium'), networkProfile: {'type': '4G', 'latency': 45}, weight: 50,
    ),
    DevicePreset(
      id: 'iphone_se_2nd', name: 'iPhone SE (2nd Gen)', category: 'mobile',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1',
      platform: 'iPhone', hardwareConcurrency: 6, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 375, screenHeight: 667, viewportWidth: 375, viewportHeight: 553,
      gpuVendor: 'Apple Inc.', gpuRenderer: 'Apple GPU', webglVersion: 'WebGL 2.0', touchPoints: 5,
      timezone: 'Europe/Paris', locale: 'fr-FR', fonts: ['San Francisco', 'Helvetica Neue', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('medium'), networkProfile: {'type': '4G', 'latency': 50}, weight: 35,
    ),

    // --- WINDOWS (Heavy Mid/Low) ---
    DevicePreset(
      id: 'thinkpad_t14_gen2', name: 'ThinkPad T14 Gen 2', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
      platform: 'Win32', hardwareConcurrency: 8, deviceMemory: 8, devicePixelRatio: 1.0,
      screenWidth: 1920, screenHeight: 1080, viewportWidth: 1920, viewportHeight: 937,
      gpuVendor: 'Google Inc. (Intel)', gpuRenderer: 'ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'Europe/Berlin', locale: 'de-DE', fonts: ['Arial', 'Segoe UI', 'Times New Roman'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp9"'],
      behaviorProfile: BehaviorProfile.getProfile('medium'), networkProfile: {'type': 'broadband', 'latency': 25}, weight: 35,
    ),
    DevicePreset(
      id: 'hp_pavilion_15', name: 'HP Pavilion 15', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
      platform: 'Win32', hardwareConcurrency: 8, deviceMemory: 8, devicePixelRatio: 1.25,
      screenWidth: 1920, screenHeight: 1080, viewportWidth: 1536, viewportHeight: 754,
      gpuVendor: 'Google Inc. (Intel)', gpuRenderer: 'ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'America/Los_Angeles', locale: 'en-US', fonts: ['Arial', 'Segoe UI', 'Times New Roman'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp9"'],
      behaviorProfile: BehaviorProfile.getProfile('medium'), networkProfile: {'type': 'broadband', 'latency': 28}, weight: 55,
    ),
    DevicePreset(
      id: 'lenovo_ideapad_3', name: 'Lenovo IdeaPad 3', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
      platform: 'Win32', hardwareConcurrency: 4, deviceMemory: 8, devicePixelRatio: 1.0,
      screenWidth: 1920, screenHeight: 1080, viewportWidth: 1920, viewportHeight: 950,
      gpuVendor: 'Google Inc. (Intel)', gpuRenderer: 'ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Arial', 'Segoe UI', 'Times New Roman'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp8"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': 'broadband', 'latency': 35}, weight: 65,
    ),
    DevicePreset(
      id: 'acer_aspire_5', name: 'Acer Aspire 5', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      platform: 'Win32', hardwareConcurrency: 4, deviceMemory: 8, devicePixelRatio: 1.0,
      screenWidth: 1920, screenHeight: 1080, viewportWidth: 1920, viewportHeight: 960,
      gpuVendor: 'Google Inc. (AMD)', gpuRenderer: 'ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'America/Sao_Paulo', locale: 'pt-BR', fonts: ['Arial', 'Segoe UI', 'Times New Roman'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"', 'video/webm; codecs="vp8"'],
      behaviorProfile: BehaviorProfile.getProfile('medium'), networkProfile: {'type': 'broadband', 'latency': 30}, weight: 60,
    ),
    DevicePreset(
      id: 'old_windows_i3', name: 'Old Windows Laptop (Intel i3)', category: 'laptop',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
      platform: 'Win32', hardwareConcurrency: 4, deviceMemory: 4, devicePixelRatio: 1.0,
      screenWidth: 1366, screenHeight: 768, viewportWidth: 1366, viewportHeight: 650,
      gpuVendor: 'Google Inc. (Intel)', gpuRenderer: 'ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11)', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 0,
      timezone: 'Asia/Manila', locale: 'en-PH', fonts: ['Arial', 'Times New Roman'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': 'broadband', 'latency': 80}, weight: 70,
    ),

    // =========================================================
    // --- 30+ LOW-MID ANDROID (Weight: 100-200 to dominate) ---
    // =========================================================
    
    // SAMSUNG
    DevicePreset(
      id: 'samsung_a10', name: 'Samsung Galaxy A10', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 9; SM-A105F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G71', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '3G/4G', 'latency': 100}, weight: 150,
    ),
    DevicePreset(
      id: 'samsung_a11', name: 'Samsung Galaxy A11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; SM-A115F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 506', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'America/Sao_Paulo', locale: 'pt-BR', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 140,
    ),
    DevicePreset(
      id: 'samsung_a12', name: 'Samsung Galaxy A12', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-A125F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Europe/Istanbul', locale: 'tr-TR', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 80}, weight: 200, // Very common
    ),
    DevicePreset(
      id: 'samsung_a13', name: 'Samsung Galaxy A13', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-A135F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.625,
      screenWidth: 400, screenHeight: 888, viewportWidth: 400, viewportHeight: 800,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 75}, weight: 190,
    ),
    DevicePreset(
      id: 'samsung_a20', name: 'Samsung Galaxy A20', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; SM-A205F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G71', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'America/Mexico_City', locale: 'es-MX', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 85}, weight: 120,
    ),
    DevicePreset(
      id: 'samsung_a21s', name: 'Samsung Galaxy A21s', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-A217F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Manila', locale: 'en-PH', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 80}, weight: 160,
    ),
    DevicePreset(
      id: 'samsung_a31', name: 'Samsung Galaxy A31', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-A315F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.625,
      screenWidth: 412, screenHeight: 915, viewportWidth: 412, viewportHeight: 830,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52 MC2', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'America/Bogota', locale: 'es-CO', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 75}, weight: 150,
    ),
    DevicePreset(
      id: 'samsung_a32', name: 'Samsung Galaxy A32', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-A325F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.625,
      screenWidth: 412, screenHeight: 915, viewportWidth: 412, viewportHeight: 830,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52 MC2', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Europe/Kyiv', locale: 'uk-UA', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 70}, weight: 180,
    ),
    DevicePreset(
      id: 'samsung_m11', name: 'Samsung Galaxy M11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-M115F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 1.75,
      screenWidth: 360, screenHeight: 775, viewportWidth: 360, viewportHeight: 690,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 506', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Dhaka', locale: 'bn-BD', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 95}, weight: 110,
    ),
    DevicePreset(
      id: 'samsung_m12', name: 'Samsung Galaxy M12', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; SM-M127F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 85}, weight: 130,
    ),

    // REDMI / XIAOMI
    DevicePreset(
      id: 'redmi_8', name: 'Xiaomi Redmi 8', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; Redmi 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 505', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 110,
    ),
    DevicePreset(
      id: 'redmi_9', name: 'Xiaomi Redmi 9', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; M2004J19G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.75,
      screenWidth: 393, screenHeight: 851, viewportWidth: 393, viewportHeight: 740,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52 MC2', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Europe/Madrid', locale: 'es-ES', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 80}, weight: 180,
    ),
    DevicePreset(
      id: 'redmi_9a', name: 'Xiaomi Redmi 9A', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; M2006C3LG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 780, viewportWidth: 360, viewportHeight: 690,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 100}, weight: 190,
    ),
    DevicePreset(
      id: 'redmi_9c', name: 'Xiaomi Redmi 9C', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; M2006C3MG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 780, viewportWidth: 360, viewportHeight: 690,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kuala_Lumpur', locale: 'ms-MY', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 150,
    ),
    DevicePreset(
      id: 'redmi_note_8', name: 'Xiaomi Redmi Note 8', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.75,
      screenWidth: 393, screenHeight: 851, viewportWidth: 393, viewportHeight: 740,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 610', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 85}, weight: 140,
    ),
    DevicePreset(
      id: 'redmi_note_9', name: 'Xiaomi Redmi Note 9', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; M2003J15SG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.75,
      screenWidth: 393, screenHeight: 851, viewportWidth: 393, viewportHeight: 740,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-G52 MC2', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Europe/Rome', locale: 'it-IT', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 80}, weight: 180,
    ),
    DevicePreset(
      id: 'redmi_note_10', name: 'Xiaomi Redmi Note 10', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 12; M2101K7AI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.75,
      screenWidth: 393, screenHeight: 851, viewportWidth: 393, viewportHeight: 740,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 612', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 75}, weight: 200,
    ),
    DevicePreset(
      id: 'redmi_note_11', name: 'Xiaomi Redmi Note 11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; 2201117TI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 6, devicePixelRatio: 2.75,
      screenWidth: 393, screenHeight: 851, viewportWidth: 393, viewportHeight: 740,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 610', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Manila', locale: 'en-PH', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 70}, weight: 220,
    ),

    // OPPO / REALME
    DevicePreset(
      id: 'oppo_a15', name: 'Oppo A15', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; CPH2185) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 780, viewportWidth: 360, viewportHeight: 690,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Jakarta', locale: 'id-ID', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 150,
    ),
    DevicePreset(
      id: 'oppo_a16', name: 'Oppo A16', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; CPH2269) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Ho_Chi_Minh', locale: 'vi-VN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 85}, weight: 160,
    ),
    DevicePreset(
      id: 'oppo_a5s', name: 'Oppo A5s', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Dhaka', locale: 'bn-BD', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 110}, weight: 100,
    ),
    DevicePreset(
      id: 'oppo_a54', name: 'Oppo A54', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; CPH2239) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 80}, weight: 170,
    ),
    DevicePreset(
      id: 'realme_c11', name: 'Realme C11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; RMX2185) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Jakarta', locale: 'id-ID', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 95}, weight: 140,
    ),
    DevicePreset(
      id: 'realme_5i', name: 'Realme 5i', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; RMX2030) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 610', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kuala_Lumpur', locale: 'ms-MY', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 85}, weight: 130,
    ),

    // VIVO
    DevicePreset(
      id: 'vivo_y11', name: 'Vivo Y11', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; vivo 1906) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 505', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Kolkata', locale: 'en-IN', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 140,
    ),
    DevicePreset(
      id: 'vivo_y12', name: 'Vivo Y12', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; vivo 1904) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 3, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Jakarta', locale: 'id-ID', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('high'), networkProfile: {'type': '4G', 'latency': 90}, weight: 150,
    ),
    DevicePreset(
      id: 'vivo_y20', name: 'Vivo Y20', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; V2027) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36',
      platform: 'Linux aarch64', hardwareConcurrency: 8, deviceMemory: 4, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 800, viewportWidth: 360, viewportHeight: 720,
      gpuVendor: 'Qualcomm', gpuRenderer: 'Adreno (TM) 610', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Manila', locale: 'en-PH', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('low_mid_android'), networkProfile: {'type': '4G', 'latency': 80}, weight: 170,
    ),
    DevicePreset(
      id: 'vivo_y91c', name: 'Vivo Y91C', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 8.1.0; vivo 1820) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 8, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 10,
      timezone: 'Asia/Dhaka', locale: 'bn-BD', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '3G/4G', 'latency': 110}, weight: 100,
    ),

    // GENERIC LOW-END
    DevicePreset(
      id: 'generic_mtk_1', name: 'Generic Mediatek Device', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 10; X657B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 4, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 720, viewportWidth: 360, viewportHeight: 640,
      gpuVendor: 'Imagination Technologies', gpuRenderer: 'PowerVR Rogue GE8320', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 5,
      timezone: 'Africa/Lagos', locale: 'en-NG', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '3G', 'latency': 130}, weight: 120,
    ),
    DevicePreset(
      id: 'generic_unisoc_1', name: 'Generic Unisoc Device', category: 'mobile',
      userAgent: 'Mozilla/5.0 (Linux; Android 11; Itel A58) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36',
      platform: 'Linux armv8l', hardwareConcurrency: 4, deviceMemory: 2, devicePixelRatio: 2.0,
      screenWidth: 360, screenHeight: 760, viewportWidth: 360, viewportHeight: 680,
      gpuVendor: 'ARM', gpuRenderer: 'Mali-T820', webglVersion: 'WebGL 2.0 (OpenGL ES 3.0 Chromium)', touchPoints: 5,
      timezone: 'Africa/Nairobi', locale: 'en-KE', fonts: ['Roboto', 'Arial'], mediaDevices: {'audioInput': 1, 'videoInput': 1, 'audioOutput': 1}, codecs: ['video/mp4; codecs="avc1.42E01E"'],
      behaviorProfile: BehaviorProfile.getProfile('very_high'), networkProfile: {'type': '3G/4G', 'latency': 120}, weight: 110,
    ),
  ];
}
