import 'package:pbrowser/models/fingerprint_config.dart';

/// JavaScript code generator for Error Stack Trace Normalization.
/// Android V8/WebView produces slightly different Error.prototype.stack
/// formatting vs Chrome Desktop. Intercepts Error to normalize stack format.
class ErrorStackSpoof {
  static String generate(FingerprintConfig config) {
    return r'''
// ===== ERROR STACK TRACE NORMALIZATION =====
// Android V8 stack traces differ from Desktop Chrome in whitespace/format.
// Normalize to Chrome Desktop "    at FunctionName (file:line:col)" format.
(() => {
  try {
    const _origErrorProto = Error.prototype;
    const _origGetter = Object.getOwnPropertyDescriptor(_origErrorProto, 'stack');

    // Normalize a single stack string to Chrome Desktop format and sanitize leaks
    const normalizeStack = (stack) => {
      if (typeof stack !== 'string') return stack;

      const lines = stack.split('\\n');
      const cleanLines = [];

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        
        // Anti-Detect: Strip our own internal identifiers and cloaks
        if (line.includes('__pbrowser') || line.includes('pbrowser')) continue;
        
        // Evasion: Strip anonymous evaluation frames (common in injected IIFEs)
        if (line.includes('<anonymous>')) continue;
        
        // Evasion: Strip Native Proxy / Reflect hooks
        if (line.includes('Proxy.') || line.includes('Reflect.apply') || line.includes('Object.apply')) {
            // Keep Object.apply if it's normal, but usually we just want to hide Proxy
            if(line.includes('Proxy.')) continue;
        }
        
        // Evasion: Strip WebView/Android evaluation bridges
        if (line.includes('Android.evaluateJavascript') || line.includes('evaluate:')) continue;
        if (line.includes('jni:') || line.includes('java.')) continue;

        // Format enforcement
        const normalizedLine = line.replace(/^\\s*at\\s+/, '    at ');
        cleanLines.push(normalizedLine);
      }

      return cleanLines.join('\\n').trim();
    };

    if (_origGetter && _origGetter.get) {
      const _origGet = _origGetter.get;
      const _spoofedGet = function() {
        // If the error object itself is generated by our proxy, hide it
        const raw = _origGet.call(this);
        try { return normalizeStack(raw); } catch(e) { return raw; }
      };
      window.__pbrowser_cloak(_spoofedGet, 'function get stack() { [native code] }');
      Object.defineProperty(Error.prototype, 'stack', {
        get: _spoofedGet,
        set: _origGetter.set,
        configurable: true,
        enumerable: _origGetter.enumerable
      });
    }

    // --- V8 Object.defineProperty(Error, 'prepareStackTrace') Interception ---
    // Advanced bots override prepareStackTrace to bypass Error.prototype.stack getter.
    // If they do, we wrap their custom formatter to filter the resulting string.
    let _userPrepareStackTrace = Error.prepareStackTrace;
    Object.defineProperty(Error, 'prepareStackTrace', {
        get: function() { 
            return _userPrepareStackTrace; 
        },
        set: function(val) {
            if (typeof val === 'function') {
                _userPrepareStackTrace = function(error, structuredStackTrace) {
                    // Pre-filter the structured stack frames to remove our ghosts
                    const cleanFrames = structuredStackTrace.filter(frame => {
                        const fname = frame.getFunctionName();
                        const script = frame.getFileNameOrScriptNameOrSourceURL && frame.getFileNameOrScriptNameOrSourceURL();
                        if (fname && (fname.includes('__pbrowser') || fname.includes('pbrowser'))) return false;
                        if (script && script.includes('<anonymous>')) return false;
                        // Avoid proxy frames
                        if (frame.isNative() && fname === 'apply') return false; 
                        return true;
                    });
                    const rawResult = val(error, cleanFrames);
                    return normalizeStack(rawResult);
                };
            } else {
                _userPrepareStackTrace = val;
            }
        },
        configurable: true,
        enumerable: true
    });

    // Also suppress V8-specific Error.captureStackTrace detection
    // FingerprintJS Pro checks for this as a V8 probe
    if (Error.captureStackTrace) {
      const _origCST = Error.captureStackTrace;
      const _spoofedCST = function(obj, constr) {
        _origCST(obj, constr);
        if (obj && obj.stack) {
          try { obj.stack = normalizeStack(obj.stack); } catch(e) {}
        }
      };
      window.__pbrowser_cloak(_spoofedCST, 'function captureStackTrace() { [native code] }');
      Error.captureStackTrace = _spoofedCST;
    }

  } catch(e) {}
})();
''';
  }
}
