import 'package:sec_tunnel/models/identity/master_identity.dart';

/// Represents a stable "Real Device Cluster" specification.
class DeviceBlueprint {
  final String family;
  final String model;
  final String brand;
  final String os;
  final String osVersion;
  final String architecture;
  final String deviceClass;
  final bool isMobile;
  
  // Hardware
  final CpuIdentity cpu;
  final GpuIdentity gpu;
  final int ram; // GB
  final int cores;
  final int touchPoints;
  
  // Display
  final ScreenIdentity screen;
  
  // Browser base
  final String userAgentTemplate;
  final int minChrome;
  final int maxChrome;

  const DeviceBlueprint({
    required this.family,
    required this.model,
    required this.brand,
    required this.os,
    required this.osVersion,
    required this.architecture,
    required this.deviceClass,
    required this.isMobile,
    required this.cpu,
    required this.gpu,
    required this.ram,
    required this.cores,
    required this.touchPoints,
    required this.screen,
    required this.userAgentTemplate,
    required this.minChrome,
    required this.maxChrome,
  });
}

class DeviceBlueprints {
  static const Map<String, List<DeviceBlueprint>> families = {
    'Google': [
      DeviceBlueprint(
        family: 'Google',
        model: 'Pixel 6',
        brand: 'Google',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Google Tensor', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G78', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.5),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 122,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Google',
        model: 'Pixel 7',
        brand: 'Google',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Tensor G2', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G710', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.5),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 124,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Google',
        model: 'Pixel 8',
        brand: 'Google',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Tensor G3', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G715', extensions: [], limits: {}),
        ram: 8,
        cores: 9,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.5),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Google',
        model: 'Pixel 8 Pro',
        brand: 'Google',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Tensor G3', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G715', extensions: [], limits: {}),
        ram: 12,
        cores: 9,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1344, height: 2992, pixelRatio: 3.5),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
    ],
    'Samsung': [
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-G991B', // Galaxy S21
        brand: 'Samsung',
        os: 'Android',
        osVersion: '13',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Exynos 2100', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G78', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 122,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-S901B', // Galaxy S22
        brand: 'Samsung',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 1', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 730', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2340, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 124,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-S911B', // Galaxy S23
        brand: 'Samsung',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 2', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 740', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2340, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; SM-S911B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-S921B', // Galaxy S24
        brand: 'Samsung',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 3', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 750', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2340, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 128,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-A346E', // Galaxy A34 (ID variant)
        brand: 'Samsung',
        os: 'Android',
        osVersion: '13',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Dimensity 1080', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G68', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2340, pixelRatio: 2.75),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 13; SM-A346E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 122,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Samsung',
        model: 'SM-A546E', // Galaxy A54 (ID variant)
        brand: 'Samsung',
        os: 'Android',
        osVersion: '13',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Exynos 1380', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G68', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2340, pixelRatio: 2.75),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 13; SM-A546E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 124,
        maxChrome: 136,
      ),
    ],
    'Xiaomi': [
      DeviceBlueprint(
        family: 'Xiaomi',
        model: '2201123G', // Xiaomi 12
        brand: 'Xiaomi',
        os: 'Android',
        osVersion: '13',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 1', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 730', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 13; 2201123G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 124,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Xiaomi',
        model: '2211133G', // Xiaomi 13
        brand: 'Xiaomi',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 2', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 740', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; 2211133G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
      DeviceBlueprint(
        family: 'Xiaomi',
        model: '23021RAAEG', // Redmi Note 12
        brand: 'Xiaomi',
        os: 'Android',
        osVersion: '13',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 685', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 610', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2400, pixelRatio: 2.75),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 13; 23021RAAEG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 122,
        maxChrome: 134,
      ),
    ],
    'Oppo': [
      DeviceBlueprint(
        family: 'Oppo',
        model: 'CPH2593', // Oppo Reno 11
        brand: 'Oppo',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Dimensity 7050', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'ARM', renderer: 'Mali-G68', extensions: [], limits: {}),
        ram: 8,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1080, height: 2412, pixelRatio: 2.75),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; CPH2593) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
    ],
    'Vivo': [
      DeviceBlueprint(
        family: 'Vivo',
        model: 'V2303', // Vivo V30
        brand: 'Vivo',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 7 Gen 3', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 720', extensions: [], limits: {}),
        ram: 12,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1260, height: 2800, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; V2303) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
    ],
    'OnePlus': [
      DeviceBlueprint(
        family: 'OnePlus',
        model: 'CPH2447', // OnePlus 11
        brand: 'OnePlus',
        os: 'Android',
        osVersion: '14',
        architecture: 'arm64',
        deviceClass: 'mobile',
        isMobile: true,
        cpu: CpuIdentity(model: 'Snapdragon 8 Gen 2', architecture: 'arm64'),
        gpu: GpuIdentity(vendor: 'Qualcomm', renderer: 'Adreno (TM) 740', extensions: [], limits: {}),
        ram: 16,
        cores: 8,
        touchPoints: 5,
        screen: ScreenIdentity(width: 1440, height: 3216, pixelRatio: 3.0),
        userAgentTemplate: 'Mozilla/5.0 (Linux; Android 14; CPH2447) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version} Mobile Safari/537.36',
        minChrome: 126,
        maxChrome: 136,
      ),
    ],
  };
}
